config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#index'
  devise_for :users, controllers: {
    confirmations: "confirmations",
    omniauth_callbacks: "auths"
  }

  resources :users, except: [ :new, :create, :destroy ]

  get "users/follow/:type" => "follow_relationships#index", as: "follow_list"
  post "users/:id/follow" => "follow_relationships#create", as: "follow"
  delete "users/:id/unfollow" => "follow_relationships#destroy", as: "unfollow"

  resources :posts do
    resources :comments, except: [ :index, :new ] do
      resources :comments, only: [ :create ]
    end
  end
  
end

app/models/comment.rb
class Comment < ApplicationRecord
  
  belongs_to :user
  belongs_to :commentable, counter_cache: true, polymorphic: true
  has_many :comments, as: :commentable, inverse_of: :commentable, dependent: :destroy
  has_one_attached :image

  validates :content, presence: true

  acts_as_followable
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  include CommentAction

  def show
  end

  def edit
  end

  def create
    inputs = comment_params.merge({ user: current_user })
    unless params[:comment_id].nil? # is this child coment?
      parrent_comment = @comment_service.get_comment(params[:comment_id])
      @comment = @comment_service.new_comment(parrent_comment, params: inputs)
    else
      @comment = @comment_service.new_comment(@post, params: inputs)
    end

    if @comment_service.save_comment(@comment)
      @user_service.notify_new_comment(current_user, @comment)
    end
    redirect_back(fallback_location: root_path)
  end

  def update
    if @comment_service.update_comment(@comment, params: comment_params)
      redirect_to post_path(@comment.commentable)
    else
      render :edit
    end
  end

  def destroy
    @comment_service.destroy_comment(@comment)
    redirect_to post_path(@post), notice: "Comment was successfully destroyed."
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :image)
  end

end

app/controllers/concerns/comment_action.rb
require 'active_support/concern'

module CommentAction

  # This module is included by CommentsController

  extend ActiveSupport::Concern

  included do
    before_action :find_comment, except: [ :create ]
    before_action :find_post, only: [ :edit, :create, :destroy ]
    before_action :is_editable, only: [ :edit, :update ]
    before_action :is_destroyable, only: [ :destroy ]
  end

  private

  def find_comment
    @comment = @comment_service.get_comment(params[:id])
  end

  def find_post
    @post = @post_service.get_post(params[:post_id])
  end

  def is_editable
    if !@comment_service.is_owner(current_user, @comment)
      flash[:notice] = "You are not allow to edit on this comment"
      redirect_back(fallback_location: root_path)
    end
  end

  def is_destroyable
    if !@comment_service.is_destroyable(current_user, @comment)
      flash[:notice] = "You are not permited on this comment"
      redirect_back(fallback_location: root_path)
    end
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: comment, local: true, url: "/posts/#{@post.id}/comments/") do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= form_with(model: @comment, local: true, url: "/posts/#{@post.id}/comments/#{@comment.id}") do |form| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% @comment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @comment.content %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>