config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#index'
  devise_for :users, controllers: {
    confirmations: "confirmations",
    omniauth_callbacks: "auths"
  }

  resources :users, except: [ :new, :create, :destroy ]

  get "users/follow/:type" => "follow_relationships#index", as: "follow_list"
  post "users/:id/follow" => "follow_relationships#create", as: "follow"
  delete "users/:id/unfollow" => "follow_relationships#destroy", as: "unfollow"

  resources :posts do
    resources :comments, except: [ :index, :new ] do
      resources :comments, only: [ :create ]
    end
  end
  
end

app/models/user.rb
class User < ApplicationRecord
	
	devise :database_authenticatable, :registerable,
				 :recoverable, :rememberable, :validatable,
				 :confirmable ,:omniauthable, omniauth_providers: [:facebook, :google_oauth2]
				 
	validates :email, presence: true, uniqueness: true
	validates :name, presence: true
	validates :avatar, presence: true
	has_one_attached :avatar
	has_many :posts, inverse_of: :owner, dependent: :destroy
	has_many :comments, dependent: :destroy

	acts_as_follower
	acts_as_followable

	attr_accessor :skip_password_validation  # virtual attribute to skip password validation while saving

	scope :all_except, -> (user) { where.not(id: user.id) }

  protected

  def password_required?
    return false if skip_password_validation
    super
  end
end

app/controllers/concerns/user_action.rb
require 'active_support/concern'

module UserAction

  # This module is included by UsersController

  extend ActiveSupport::Concern

  included do
    before_action :find_user, only: [ :edit, :update ]
    before_action :is_current_user, only: [ :edit, :update ]
    skip_before_action :finish_profile, only: [ :edit, :update ]
  end

  private
  
  def find_user
    @user = @user_service.get_user(params[:id])
  end

  def is_current_user
    if !@user_service.is_current_user(current_user.id, @user.id)
      flash[:notice] = "You are not allow for this operation"
      redirect_back(fallback_location: root_path)
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  include UserAction

  def index
    @users = @user_service.get_all_except(current_user)
  end

  def show
    @user = @user_service.find_user(current_user, params[:id])
    redirect_back(fallback_location: root_path) if @user.nil?
  end

  def edit
  end

  def update
    if @user_service.update_user(@user, user_params)
      flash[:notice] = "Your profile has been update!"
    else
      flash[:notice] = user.errors
    end
    redirect_back(fallback_location: root_path)
  end
  
  private

  def user_params
  	params.require(:user).permit(:name, :avatar, :cover_photo, :email, :date_of_birth)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<% content_for :head do %>
  <div class="cover_photo">
	</div>
  <table>
    <tr>
      <td>
        <div class="avatar_name">
          <h3><%= current_user.name %></h3>
        </div>
      </td>
    </tr>
  </table>
<% end %>
<div style="height: 50px"></div>

<div align="center">
	<div>
		<%= form_for @user do |f| %>
			<% if @user.errors.any? %>
				<% @user.errors.full_messages.each do |mess| %>
					<%= mess %>
				<% end %>
			<% end %>
			<div class="input-group input_group">
				<label class="col-lg-2">Name</label>
				<div class="col-lg-10">
					<%= f.text_field :name, required: true, class: "form-control" %><br/><br/>
				</div>
			</div>
			<div class="input-group input_group">
				<label class="col-lg-2">Avatar</label>
				<div class="col-lg-10">
					<%= f.file_field :avatar, class: "form-control" %><br/><br/>
				</div>
			</div>
			<div class="input-group input_group">
				<label class="col-lg-2">Cover photo</label>
				<div class="col-lg-10">
					<%= f.file_field :cover_photo, class: "form-control" %><br/><br/>
				</div>
			</div>
			<div class="input-group input_group">
				<label class="col-lg-2">Email</label>
				<div class="col-lg-10">
					<%= f.email_field :email, required: true, class: "form-control" %><br/><br/>
				</div>
			</div>
      <div class="input-group input_group">
				<label class="col-lg-2">Date of birth</label>
				<div class="col-lg-10">
					<%= f.date_field :date_of_birth, required: true, class: "form-control" %><br/><br/>
				</div>
			</div>
			<%= f.submit "Update Profile", class: "btn btn-primary update_profile" %>
		<% end %>
	</div>
</div>

app/views/users/index.html.erb
<div class="container">
	<h2>All User</h2>
	<% @users.each do |user| %>
		<div class="row user_list">
			<div class="col-xs-1" style="height: 10px, width: 10px">
				<%= image_tag user.avatar, alt: "user_avatar", class: "user_avatar" %>
			</div>
			<div class="col-xs-2">
				<%= link_to user.name, user_path(user) %>
      </div>
      <% if !current_user.following?(user) %>
        <div class="col-xs-2">
          <%= link_to "Follow", follow_path(user), method: :post, class: "btn btn-success login" %>
        </div>
      <% else %>
        <div class="col-xs-2">
          <%= link_to "Unfollow", unfollow_path(user), method: :delete, class: "btn btn-danger login" %>
        </div>
      <% end %>
		</div>
	<% end %>
</div>

app/views/users/new.html.erb
<div align="center">
	<div class="form_sign_in">
		<label><h1>Sign up</h1></label>
		<br/>
		Create a new account to Open List or
		<%= link_to 'Sign in', log_in_path, style: "color: #FF8662" %>
		<br/><br/>
		<%= form_for @user do |f| %>
			<% if @user.errors.any? %>
				<% @user.errors.full_messages.each do |mess| %>
					<%= mess %>
				<% end %>
			<% end %>
			<div class="input-group" class="input_field">
				<%= f.text_field :name, required: true, class: "form-control", placeholder: "Full Name" %><br/><br/>
				<%= f.email_field :email, required: true, class: "form-control", placeholder: "Email" %><br/><br/>
				<%= f.password_field :password, required: true, class: "form-control", placeholder: "Password" %><br/><br/>
				<%= f.password_field :password_confirmation, required: true, class: "form-control", placeholder: "Password confirmation" %><br/><br/>
			</div>
			<input type="checkbox" name="remember" value="true">
			I accept the <a href="" style="color: #FF8662">Terms and Services</a><br/>
			<%= f.submit "Sign in", class: "btn btn-warning", style: "width: 50%; background-color: #FF8662" %>
		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div style="height:100px;">
  </div>
    <div class="col-xs-1" style="height: 10px, width: 10px">
      <%= image_tag @user.avatar, alt: "user_avatar", class: "user_avatar" %>
    </div>
    <div class="col-xs-2">
      <%= link_to @user.name, user_path(@user) %>
    </div>
</div>