config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#index'
  devise_for :users, controllers: {
    confirmations: "confirmations",
    omniauth_callbacks: "auths"
  }

  resources :users, except: [ :new, :create, :destroy ]

  get "users/follow/:type" => "follow_relationships#index", as: "follow_list"
  post "users/:id/follow" => "follow_relationships#create", as: "follow"
  delete "users/:id/unfollow" => "follow_relationships#destroy", as: "unfollow"

  resources :posts do
    resources :comments, except: [ :index, :new ] do
      resources :comments, only: [ :create ]
    end
  end
  
end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :owner, class_name: "User", counter_cache: true, foreign_key: "user_id"
  has_many_attached :images, dependent: :destroy
  has_many :comments, as: :commentable, inverse_of: :commentable, dependent: :destroy

  validates :title, presence: true
  validates :content, presence: true
  validates :images, presence: true

  acts_as_followable

end

app/controllers/concerns/post_action.rb
require 'active_support/concern'

module PostAction

  # This module is included by PostsController

  extend ActiveSupport::Concern

  included do
    before_action :find_post, only: [ :show, :edit, :update, :destroy ]
    before_action :is_owner, only: [ :edit, :update, :destroy ]
  end

  private

  def find_post
    @post = @post_service.get_post(params[:id])
  end

  def is_owner
    if !@post_service.is_owner(current_user, @post)
      flash[:notice] = "You are not owner of this post."
      redirect_back(fallback_location: root_path)
    end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  include PostAction

  def index
    @posts = @post_service.get_all_posts
  end

  def show
    @comment = @comment_service.new_comment(@post)
    @comments = @comment_service.get_all_comments(@post)
  end

  def new
    @post = @post_service.new_post(current_user)
  end

  def edit
  end

  def create
    @post = @post_service.new_post(current_user, params: post_params)

    if @post_service.save_post(@post)
      redirect_to @post, notice: "Post was successfully created."
      @user_service.notify_new_post(current_user, @post)
    else
      render :new
    end
  end

  def update
    if @post_service.update_post(@post, post_params)
      redirect_to @post, notice: "Post was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @post_service.destroy_post(@post)
    redirect_to posts_url, notice: 'Post was successfully destroyed.'
  end

  private

  def post_params
    params.require(:post).permit(:title, :content, :comments_count, images: [])
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>

  <div class="field">
    <%= form.label :images %>
    <%= form.file_field :images, multiple: true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Images</th>
      <th>User</th>
      <th>Comments count</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <div style="height: 10px"></div>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td>
          <% post.images.each do |image| %>
            <%= image_tag image %>
          <% end %>
        </td>
        <td><%= post.user_id %></td>
        <td><%= post.comments_count %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<p>
  <strong>Images:</strong>
  <% @post.images.each do |image| %>
    <%= image_tag image %>
  <% end %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user_id %>
</p>

<p>
  <strong>Comments count:</strong>
  <%= @post.comments_count %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

</br>
<h3>Add comment</h3>
<%= render partial: "comments/form", locals: { comment: @comment, post_id: @post.id } %>

<h1>comments</h1>

<table>
  <thead>
    <tr>
      <th>Owner</th>
      <td>|</td>
      <th>Content</th>
      <td>|</td>
      <th>Image</th>
      <td>|</td>
      <th>Operations</th>
      <td>|</td>
      <th>Comments</th>
      <td>|</td>
      <th>Add sub comment</th>
      <td>|</td>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.user.email %></td>
        <td>|</td>
        <td><%= comment.content %></td>
        <td>|</td>
        <td>
          <% if !comment.image.blank? %>
            <%= image_tag comment.image, alt: "comment_image", class: "comment_avatar" %>
          <% else %>
            comment_image
          <% end %>
        </td>
        <td>|</td>
        <td><%= link_to 'Edit', edit_post_comment_path(@post, comment) %></td>
        <td>
          <%= 
            link_to "Destroy",
              "/posts/#{@post.id}/comments/#{comment.id}",
              method: :delete,
              data: { confirm: "Are you sure?" }
          %>
        </td>
        <td>
          <% comment.comments.each do |cmt| %>
            <p><%= cmt.user.email %></p>
            <p><%= cmt.content %></p>
          <% end %>
        </td>
        <td>
          <%= form_with(model: Comment.new, local: true, url: "/posts/#{@post.id}/comments/#{comment.id}/comments") do |fm| %>
            <div class="field">
              <%= fm.label :content %>
              <%= fm.text_area :content %>
              <%= fm.label :image %>
              <%= fm.file_field :image %>
            </div>

            <div class="actions">
              <%= fm.submit %>
            </div>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>