config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#index'
  devise_for :users, controllers: {
    confirmations: "confirmations",
    omniauth_callbacks: "auths"
  }

  resources :users, except: [ :new, :create, :destroy ]

  get "users/follow/:type" => "follow_relationships#index", as: "follow_list"
  post "users/:id/follow" => "follow_relationships#create", as: "follow"
  delete "users/:id/unfollow" => "follow_relationships#destroy", as: "unfollow"

  resources :posts do
    resources :comments, except: [ :index, :new ] do
      resources :comments, only: [ :create ]
    end
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  
  belongs_to :user
  belongs_to :commentable, counter_cache: true, polymorphic: true
  has_many :comments, as: :commentable, inverse_of: :commentable, dependent: :destroy
  has_one_attached :image

  validates :content, presence: true

  acts_as_followable
  
end

app/models/follow.rb
class Follow < ActiveRecord::Base

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" interface, and also to followers
  belongs_to :followable, :polymorphic => true
  belongs_to :follower,   :polymorphic => true

  def block!
    self.update_attribute(:blocked, true)
  end

end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :owner, class_name: "User", counter_cache: true, foreign_key: "user_id"
  has_many_attached :images, dependent: :destroy
  has_many :comments, as: :commentable, inverse_of: :commentable, dependent: :destroy

  validates :title, presence: true
  validates :content, presence: true
  validates :images, presence: true

  acts_as_followable

end

app/models/user.rb
class User < ApplicationRecord
	
	devise :database_authenticatable, :registerable,
				 :recoverable, :rememberable, :validatable,
				 :confirmable ,:omniauthable, omniauth_providers: [:facebook, :google_oauth2]
				 
	validates :email, presence: true, uniqueness: true
	validates :name, presence: true
	validates :avatar, presence: true
	has_one_attached :avatar
	has_many :posts, inverse_of: :owner, dependent: :destroy
	has_many :comments, dependent: :destroy

	acts_as_follower
	acts_as_followable

	attr_accessor :skip_password_validation  # virtual attribute to skip password validation while saving

	scope :all_except, -> (user) { where.not(id: user.id) }

  protected

  def password_required?
    return false if skip_password_validation
    super
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	include ApplicationAction
	include ServiceAction

end

app/controllers/auths_controller.rb
class AuthsController < Devise::OmniauthCallbacksController
  
  def facebook
    oauth_auth
  end

  def google_oauth2
    oauth_auth
  end

  private

  def oauth_auth
    user = UserService.new.find_or_create_from_auth(request.env["omniauth.auth"])
    sign_in_and_redirect user
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  include CommentAction

  def show
  end

  def edit
  end

  def create
    inputs = comment_params.merge({ user: current_user })
    unless params[:comment_id].nil? # is this child coment?
      parrent_comment = @comment_service.get_comment(params[:comment_id])
      @comment = @comment_service.new_comment(parrent_comment, params: inputs)
    else
      @comment = @comment_service.new_comment(@post, params: inputs)
    end

    if @comment_service.save_comment(@comment)
      @user_service.notify_new_comment(current_user, @comment)
    end
    redirect_back(fallback_location: root_path)
  end

  def update
    if @comment_service.update_comment(@comment, params: comment_params)
      redirect_to post_path(@comment.commentable)
    else
      render :edit
    end
  end

  def destroy
    @comment_service.destroy_comment(@comment)
    redirect_to post_path(@post), notice: "Comment was successfully destroyed."
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :image)
  end

end

app/controllers/concerns/post_action.rb
require 'active_support/concern'

module PostAction

  # This module is included by PostsController

  extend ActiveSupport::Concern

  included do
    before_action :find_post, only: [ :show, :edit, :update, :destroy ]
    before_action :is_owner, only: [ :edit, :update, :destroy ]
  end

  private

  def find_post
    @post = @post_service.get_post(params[:id])
  end

  def is_owner
    if !@post_service.is_owner(current_user, @post)
      flash[:notice] = "You are not owner of this post."
      redirect_back(fallback_location: root_path)
    end
  end

end

app/controllers/confirmations_controller.rb
# frozen_string_literal: true

class ConfirmationsController < Devise::ConfirmationsController

  # GET /resource/confirmation/new
  def new
    super
  end

  # POST /resource/confirmation
  def create
    super
  end

  # GET /resource/confirmation?confirmation_token=abcdef
  def show
    super
    @user_service.send_welcome_email(resource) if resource.errors.empty?
  end

  protected

  # The path used after resending confirmation instructions.
  def after_resending_confirmation_instructions_path_for(resource_name)
    super(resource_name)
  end

  # The path used after confirmation.
  def after_confirmation_path_for(resource_name, resource)
    super(resource_name, resource)
  end

end

app/controllers/follow_relationships_controller.rb
class FollowRelationshipsController < ApplicationController

  FOLLOWING = "following"
  FOLLOWER = "follower"

  def index
    case params[:type]
    when FOLLOWING
      @users = @user_service.get_following_of(current_user)
    when FOLLOWER
      @users = @user_service.get_follower_of(current_user)
    end
    @users = [] if @users.nil?
    render "users/index"
  end

  def create
    @user_service.start_follow(
      current_user,
      @user_service.get_user(params[:id])
    )
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @user_service.stop_follow(
      current_user,
      @user_service.get_user(params[:id])
    )
    redirect_back(fallback_location: root_path)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  include PostAction

  def index
    @posts = @post_service.get_all_posts
  end

  def show
    @comment = @comment_service.new_comment(@post)
    @comments = @comment_service.get_all_comments(@post)
  end

  def new
    @post = @post_service.new_post(current_user)
  end

  def edit
  end

  def create
    @post = @post_service.new_post(current_user, params: post_params)

    if @post_service.save_post(@post)
      redirect_to @post, notice: "Post was successfully created."
      @user_service.notify_new_post(current_user, @post)
    else
      render :new
    end
  end

  def update
    if @post_service.update_post(@post, post_params)
      redirect_to @post, notice: "Post was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @post_service.destroy_post(@post)
    redirect_to posts_url, notice: 'Post was successfully destroyed.'
  end

  private

  def post_params
    params.require(:post).permit(:title, :content, :comments_count, images: [])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  include UserAction

  def index
    @users = @user_service.get_all_except(current_user)
  end

  def show
    @user = @user_service.find_user(current_user, params[:id])
    redirect_back(fallback_location: root_path) if @user.nil?
  end

  def edit
  end

  def update
    if @user_service.update_user(@user, user_params)
      flash[:notice] = "Your profile has been update!"
    else
      flash[:notice] = user.errors
    end
    redirect_back(fallback_location: root_path)
  end
  
  private

  def user_params
  	params.require(:user).permit(:name, :avatar, :cover_photo, :email, :date_of_birth)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/follow_relationships_helper.rb
module FollowRelationshipsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Social Network</title>

    <%= csrf_meta_tags %>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
		<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style>
    	body {
    		background-color: <%= current_user.color if current_user %>;
    	}
    </style>
  </head>

  <body class="non_responsive">
	  <% if current_user %>
			<nav class="navbar navbar-default nav_bar navbar-fixed-top">
				<div class="col-xs-1"></div>
				<div class="col-xs-10">
					<div class="container-fluid">
				    <div class="navbar-header">
				    	<%= image_tag("/icon/brand.png", alt: "brand_icon") %>
				    </div>
				    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				      <div class="navbar-form navbar-left">
				      	<ul class="nav navbar-nav">
				      		<li><%= link_to "HOME", root_path %></li>
				      		<li><a href="">ALL PAGES</a></li>
				      		<li><a href="">SHORTCODES</a></li>
									<li><a href="">ALL ELEMENT</a></li>
									<li>
										<%= link_to users_path do %>
											<span class="glyphicon glyphicon-user"></span>
											All users
										<% end %>
									</li>
									<li>
										<%= link_to follow_list_path(type: "following") do %>
											<span class="glyphicon glyphicon-user"></span>
											Following users
										<% end %>
									</li>
									<li>
									<%= link_to follow_list_path(type: "follower") do %>
											<span class="glyphicon glyphicon-user"></span>
											Followers
										<% end %>
									</li>
									<li>
										<%= link_to edit_user_path(current_user) do %>
											<span class="glyphicon glyphicon-pencil"></span>
											Edit profiles
										<% end %>
									</li>
									<li>
									<%= link_to destroy_user_session_path, :method => :delete do %>
										<span class="glyphicon glyphicon-off"></span>
										Log out
									<% end %>
									</li>
				      	</ul>
				      </div>
				      <div class="navbar-form navbar-right">
				      	<div class="btn-group">
								  <div data-toggle="dropdown">
								  	<a href="">
								  		<span class="num_of_notificcation pink_noti"></span>
								  		<span class="glyphicon glyphicon-user glyphicon_noti"></span>
								  	</a>
								  </div>
								  <ul class="dropdown-menu dropdown_menu">
									  <div class="container">
									  	<li>
									  		All requests
									  	</li>
									  </div>
								  	<li role="separator" class="divider"></li>
								  </ul>
								</div>
								<div class="btn-group">
								  <div data-toggle="dropdown">
								  	<a href="">
								  		<span class="num_of_notificcation green_noti"></span>
								  		<span class="glyphicon glyphicon-comment glyphicon_noti"></span>
								  	</a>
								  </div>
								  <ul class="dropdown-menu dropdown_menu">
                    <div class="container">
                    </div>
								  	<li role="separator" class="divider"></li>
								  </ul>
								</div>
				      	<div class="btn-group">
								  <div data-toggle="dropdown">
								  	<a href="">
								  		<span class="num_of_notificcation orange_noti"></span>
								  		<span class="glyphicon glyphicon-bell glyphicon_noti"></span>
								  	</a>
								  </div>
								  <ul class="dropdown-menu dropdown_menu">
										<div class="container">
									  	<li>All notifications</li>
									  </div>
								  	<li role="separator" class="divider"></li>
								  </ul>
								</div>
								<div class="btn-group">
								  <div data-toggle="dropdown">
								  </div>
								  <ul class="dropdown-menu">
                    <li>
								  		<a href="">
								  			<span class="glyphicon glyphicon-folder-close"></span>
								  			Saved Articles
								  		</a>
								  	</li>
								  	<li role="separator" class="divider"></li>
								  	<li role="separator" class="divider"></li>
										<li>
								  		<a href="">
									  		<span class="glyphicon glyphicon-bell"></span>
									  		Notification settings
								  		</a>
								  	</li>
								  	<li>
								  		<a href="">
									  		<span class="glyphicon glyphicon-lock"></span>
									  		Change Password
								  		</a>
								  	</li>
										<li role="separator" class="divider"></li>
										<li>
								  		<a href="">
								  			<span class="glyphicon glyphicon-cog"></span>
								  			Settings
								  		</a>
								  	</li>
								  	<li>
								  		<a href="">
								  			<span class="glyphicon glyphicon-flag"></span>
								  			Private Policy
								  		</a>
								  	</li>
								  	<li>
								  		<a href="">
								  			<span class="glyphicon glyphicon-stats"></span>
								  			FAQ
								  		</a>
								  	</li>
								  	<li>
								  		<%= link_to destroy_user_session_path, :method => :delete do %>
								  			<span class="glyphicon glyphicon-off"></span>
								  			Log out
								  		<% end %>
								  	</li>
								  </ul>
								</div>
				      </div>
				    </div>
				  </div>
				</div>
				<div class="col-xs-1"></div>
			</nav>
			<div class="virtual_nav"></div>
			<%= yield :head %>
			<div class="row">
				<div style="height: 100px"></div>
				<div class="container">
				  <div class="col-xs-7">
					  <% if flash[:notice] %>
					  	<div class="alert-info" align="center">
					  		<%= flash[:notice] %>
					  	</div>
					  <% end %>
					  <div class="yield_content">
					  	<%= yield %>
					  </div>
				  </div>
				</div>
			</div>
		<% else %>
			<div class="container" align="center">
				<div class="alert-success">
					<% if notice %>
			  		<%= notice %>
			  	<% end %>
		  	</div>
		  	<div class="alert-danger">
			  	<% if alert %>
			  		<%= alert %>
			  	<% end %>
		  	</div>
				<%= yield %>
			</div>
		<% end %>
	</body>
</html>

app/views/pages/index.html.erb
<p>This is index of Page</p>